# Basic Developer Setup
install apple-gcc42
install c-ares
install ctags
install ec2-api-tools
install elixir
install erlang
install git
install libyaml
install macvim
install mongodb
install node
install openssl
install postgresql
install pow
install readline
install reattach-to-user-namespace
install redis
install sqlite
install the_silver_searcher
install tmux
install zsh
brew todo-txt
